name: kerchunk-test

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - h5py
  - zarr
  - requests
  - aiohttp
  - fsspec
  - xarray
  - matplotlib
  - jinja2
  - pip:
    - kerchunk
